// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface AtomIconTitlePairStoryblok {
  name: string;
  icon: string;
  iconSize?: string;
  component: "atomIconTitlePair";
  _uid: string;
  [k: string]: any;
}

export type MultilinkStoryblok =
  | {
      id?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "story";
      target?: "_self" | "_blank";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {
          [k: string]: any;
        };
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {
          [k: string]: any;
        };
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: any[];
        default_full_slug?: null | string;
        translated_slugs?: null | any[];
        [k: string]: any;
      };
      [k: string]: any;
    }
  | {
      url?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "asset" | "url";
      target?: "_self" | "_blank";
      [k: string]: any;
    }
  | {
      email?: string;
      linktype?: "email";
      target?: "_self" | "_blank";
      [k: string]: any;
    };

export interface AtomSingleLinkStoryblok {
  link: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  displayText?: string;
  component: "atomSingleLink";
  _uid: string;
  [k: string]: any;
}

export interface DataDiscountedParkingOptionStoryblok {
  time?: string;
  cost?: string;
  component: "dataDiscountedParkingOption";
  _uid: string;
  [k: string]: any;
}

export interface FeatureStoryblok {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: any;
}

export interface GridStoryblok {
  columns?: (
    | AtomIconTitlePairStoryblok
    | AtomSingleLinkStoryblok
    | DataDiscountedParkingOptionStoryblok
    | FeatureStoryblok
    | GridStoryblok
    | MetaSiteOptionsStoryblok
    | SectionIconListStoryblok
    | TeaserStoryblok
    | TemplatePageStoryblok
  )[];
  component: "grid";
  _uid: string;
  [k: string]: any;
}

export interface MetaSiteOptionsStoryblok {
  telephone?: string;
  email?: string;
  navigation?: AtomSingleLinkStoryblok[];
  discountedParking?: DataDiscountedParkingOptionStoryblok[];
  component: "metaSiteOptions";
  _uid: string;
  [k: string]: any;
}

export interface SectionIconListStoryblok {
  title?: string;
  icons?: AtomIconTitlePairStoryblok[];
  component: "sectionIconList";
  _uid: string;
  [k: string]: any;
}

export interface TeaserStoryblok {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: any;
}

export interface TemplatePageStoryblok {
  body?: SectionIconListStoryblok[];
  component: "templatePage";
  _uid: string;
  [k: string]: any;
}
